### ISSUE TITLE
Add a ScrollBar inside the Board

### ISSUE THREAD

**Issue by brunonetadmin** [riktar/jkanban#33]
Add support to a native or at least, to custom Scrollbars (like SlimScroll), right now, the component that holds the items don´t support this, at least not without losing the drag-and-drop functionality.

Thanks.

**Comment by marcosrocha85** [comment]
Hello @brunonetadmin , I achieved scrollbar by doing some CSS modifications to built DOM of jKanban. Just after initialize I set my main div to full height.
```css
.full-height {
    min-height: 100%;
    height: 100%;
    max-height: 100%;
}
.board-full-height {
    min-height: 100%;
    height: 100%;
    max-height: 100%;
    overflow-y: hidden;
}
.drag-full-height {
    min-height: 100%;
    height: 100%;
    max-height: 100%;
    overflow-y: auto;
}
```
And then I sought for class kanban-container adding also full height to it:
```javascript
jkanban = new jKanban({
    //... just initialization stuff
});

var x = document.getElementsByClassName("kanban-container");
var i;
for (i = 0; i < x.length; i++) {
    var _attribute = x[i].getAttribute("class");
    x[i].setAttribute("class", _attribute + " full-height");
} 
```
Of course each board has to be set to full-heigt as well:
```javascript
var x = document.getElementsByClassName("kanban-board");
var i;
for (i = 0; i < x.length; i++) {
    var _attribute = x[i].getAttribute("class");
    x[i].setAttribute("class", _attribute + " board-full-height");
} 
```
And finally set kanban-drag to overflow-auto:
```javascript
var x = document.getElementsByClassName("kanban-drag");
var i;
for (i = 0; i < x.length; i++) {
    var _attribute = x[i].getAttribute("class");
    x[i].setAttribute("class", _attribute + " drag-full-height");
} 
```
Then I have a result like this:
![image](https://user-images.githubusercontent.com/7257227/47652284-483d7580-db64-11e8-8444-a07ac2c81690.png)
